### PR TITLE
[United States] Add military and outlying territory administrative areas

### PR DESCRIPTION
**Pull request by eugenio-bolt**
* This fixes an issue where US addresses to APO boxes are invalid
* It also includes US territory areas, which follow the US mailing standard

### CODE REVIEW

**Comment by F21** [comment]
Hey, thanks for opening this PR!

Just a quick question regarding the following territories that were added under United States: `GU`, `MH`, `FM`, `MP`, `PW`, `PR`, VI`.

Those codes are already included in the data at the highest level as countries themselves. I did have a look around the web and my findings were:
- For Amazon shipping addresses, they allowed selecting those codes as either a country or as a state under the United States.
- For Microsoft addresses, those territories were not available as states under the United States and were only available as countries.

I have never sent international mail to those territories, so I am not quite sure how they are addressed and the UPU documentation is quite sparse and does not include any examples, for example for Guam: https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/gumEn.pdf

If these territories were included as states under the United States, formatting an address for international mailing will include `United States` as the country:
````
John Citizen
525 Some Street
Some City, Guam 96912
United States
````
Is this the correct way for addressing mail to Guam?

Another doubt is Palau (`PW`). It seems to be an independent country that uses the US addressing format: https://youbianku.com/files/upu/PLW.pdf If we were to select it as a state of the US and address international mail, it would format as:

```
John Citizen
525 Some Street
Some City, Palau 96940
United States
```
This seems a bit odd as Palau seems to be an independent country and it's not clear if the mail would be delivered. At the same time, this blog post states that the country must be marked as `United States` when posting to those territories (including Palau): https://www.grogtag.com/blog/169/how-should-i-write-the-address-to-a-us-territory

As I don't live in the US and have never posted any mail to US territories, I am not sure what is the correct way to address the territories.

- Should we include the territories as independent countries as we currently do, or should those entries be removed?
- Should those territories (`GU`, `MH`, `FM`, `MP`, `PW`, `PR`, VI`) be included as subdivisions in the US or should they be removed?

I'll try to contact Australia Post to see what they recommend for mailing to those destinations, but if you can confirm the above we and plot a clear course to get this PR merged.

**Comment by eugenio-bolt** [comment]
> Hey, thanks for opening this PR!
> 
> Just a quick question regarding the following territories that were added under United States: `AS`, `GU`, `MH`, `FM`, `MP`, `PW`, `PR`, `VI`.
> 
> Those codes are already included in the data at the highest level as countries themselves. I did have a look around the web and my findings were:
> 
> * For Amazon shipping addresses, they allowed selecting those codes as either a country or as a state under the United States.
> * For Microsoft addresses, those territories were not available as states under the United States and were only available as countries.
> 
> I have never sent international mail to those territories, so I am not quite sure how they are addressed and the UPU documentation is quite sparse and does not include any examples, for example for Guam: https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/gumEn.pdf
> 
> If these territories were included as states under the United States, formatting an address for international mailing will include `United States` as the country:
> 
> ```
> John Citizen
> 525 Some Street
> Some City, Guam 96912
> United States
> ```
> 
> Is this the correct way for addressing mail to Guam?
> 
> Another doubt is Palau (`PW`). It seems to be an independent country that uses the US addressing format: https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/plwEn.pdf If we were to select it as a state of the US and address international mail, it would format as:
> 
> ```
> John Citizen
> 525 Some Street
> Some City, Palau 96940
> United States
> ```
> 
> This seems a bit odd as Palau seems to be an independent country and it's not clear if the mail would be delivered. At the same time, this blog post states that the country must be marked as `United States` when posting to those territories (including Palau): https://www.grogtag.com/blog/169/how-should-i-write-the-address-to-a-us-territory
> 
> As I don't live in the US and have never posted any mail to US territories, I am not sure what is the correct way to address the territories.
> 
> * Should we include the territories as independent countries as we currently do, or should those entries be removed?
> * Should those territories (`AS`, `GU`, `MH`, `FM`, `MP`, `PW`, `PR`, `VI`) be included as subdivisions in the US or should they be removed?
> 
> I'll try to contact Australia Post to see what they recommend for mailing to those destinations, but if you can confirm the above we and plot a clear course to get this PR merged.
> 
> Ref in libaddressinput: [google/libaddressinput#55](https://github.com/google/libaddressinput/issues/55)

Hi!

Great questions. In terms of USPS guidelines, mail sent to freely associated US states (e.g. Palau) is [treated as domestic](https://faq.usps.com/s/article/What-US-Possessions-US-Territories-and-Freely-Associated-States-are-Considered-Domestic) and is routed using US ZIP codes.

The same UPU guidelines you posted also apply to other examples, such as the [U.S. Virgin Islands](https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/virEn.pdf), which also has its own ISO 3166-1 code (`VI`).

In general, regardless of wether or not an address if "valid," there will be pecularities regarding specific territories that are outside the scope of this library to identify. For example, if shipping to Guam is restricted, that's up to the library's user to determine. Similar restrictions apply to non-mainland U.S. states (e.g. Hawaii), but we wouldn't be debating whether or not that logic belongs in a library related to address validation.

I would stick to the stated goal:
```
Address is a Go library that validates and formats addresses using data generated from Google's Address Data Service
```

My rationale would be that since these sub-divisions are included in Google's data, and since addresses formatted using these sub-divisions are considered valid, that the library should handle them accordingly. A user can apply more restrictive logic on top of this library if they desire.

I appreciate you reviewing the code so soon -- I just started toying around with this library and am pretty excited about being able to use it long-term (and hopefully contribute some more).

**Comment by F21** [comment]
So I just contacted Australia Post as well and they were not able to give me a any definite answers in terms of addressing mail to those territories.

Just wanted to clarify the situation for Palau, if I address a letter as the following:
```
John Citizen
525 Some Street
Some City, Palau 96940
United States
```
Will it arrive at it's destination? Or would I have to use this:
```
John Citizen
525 Some Street
Some City, Palau 96940
```
This is given that Palau Post as the following address in their footer (http://www.palaupost.pw/contact.aspx):
```
P.O. BOX 1982 KOROR, REPUBLIC OF PALAU 96940
```
Thanks!

**Comment by eugenio-bolt** [comment]
> So I just contacted Australia Post as well and they were not able to give me a any definite answers in terms of addressing mail to those territories.
> 
> Just wanted to clarify the situation for Palau, if I address a letter as the following:
> 
> ```
> John Citizen
> 525 Some Street
> Some City, Palau 96940
> United States
> ```
> 
> Will it arrive at it's destination? Or would I have to use this:
> 
> ```
> John Citizen
> 525 Some Street
> Some City, Palau 96940
> ```
> 
> This is given that Palau Post as the following address in their footer (http://www.palaupost.pw/contact.aspx):
> 
> ```
> P.O. BOX 1982 KOROR, REPUBLIC OF PALAU 96940
> ```
> 
> Thanks!

My understanding is that the "proper" address format for Palau includes `UNITED STATES OF AMERICA` as the country (e.g. https://www.informatica.com/products/data-quality/data-as-a-service/address-verification/address-formats.html?code=PLW)

This seems to match what is indicated in the UPU document you linked (too bad they don't provide an explicit example)

**Comment by F21** [comment]
Thanks, that makes a lot of sense. The last remaining issue is that those territories are currently listed at the top level (as a country) as well, so it's not clear if we should remove those entries.

For Amazon, it seems they include the territories as states of the US and as countries.
For Microsoft, they are not included as states and only as countries.

I suppose we could keep them as both countries and states as this PR does currently (as in Amazon's case) as well, but I am sort of on the fence regarding this.

**Comment by eugenio-bolt** [comment]
> Thanks, that makes a lot of sense. The last remaining issue is that those territories are currently listed at the top level (as a country) as well, so it's not clear if we should remove those entries.
> 
> For Amazon, it seems they include the territories as states of the US and as countries. For Microsoft, they are not included as states and only as countries.
> 
> I suppose we could keep them as both countries and states as this PR does currently (as in Amazon's case) as well, but I am sort of on the fence regarding this.

I would suggest keeping them, since that matches Google's data. I also feel it might be riskier for this library to 
*remove* keys, since it's possible that data has been stored in database with these identifiers (although keys can be removed when countries cease to exist, or reorganize, so some level of resilience should be warranted)

**Comment by F21** [comment]
Sounds good to me! I'll merge this and tag a new release. Thanks for contributing this PR :)

**Pull request merged**
