### PR TITLE
Updated data.generated.go

### PR DESCRIPTION
**Pull request by ping-localhost**
I've updated the `data.generated.go`-file and dependencies so that everything is back on latest.

### CODE REVIEW

**Comment by ping-localhost** [comment]
Failing test is unrelated to PR:
image

**Comment by F21** [comment]
Thanks! Looks good to me, I'll fix the github actions to only trigger codeclimate on push to master.

**Comment by ping-localhost** [comment]
Would it be possible to run a GitHub Action once in awhile to see if the `data.generated.go` has any changes? 🤔

**Comment by F21** [comment]
It's possible to create a cron job in actions to check if `data.generate.go` changes. The problem is how to signal that the file is out of date. I don't think actions provide a way to store a generated badge to signal this, and I don't want to make a commit to the repo to generate the badge as we would have tons of commits that are unrelated to the code.

**Comment by ping-localhost** [comment]
Why not make a PR instead of doing a badge? Haven't looked into GitHub actions yet, so I don't know if that's possible, but that should be a very clear signal. 😜

**Comment by F21** [comment]
That sounds like a pretty good idea! I think using something like the [Create Pull Request action](https://github.com/marketplace/actions/create-pull-request) would probably get us most of the way there :)

**Pull request merged**
